# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '14.0'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  pod 'RNHerme', :path => '../node_modules/react-native/third-party/hermes-engine'
  use_frameworks! :linkage => linkage.to_sym
end

target 'vaarahimart' do
  # React Native Maps dependencies

rn_maps_path = '../node_modules/react-native-maps'
pod 'react-native-google-maps', :path => rn_maps_path
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'vaarahimartTests' do
    inherit! :complete
    # Pods for testing
  end

  # permissions_path = '../node_modules/react-native-permissions/ios'

  #   pod 'permission.CAMERA', :path => "#{permissions_path}/Camera"
  #   pod 'permission.PHOTO_LIBRARY', :path => "#{permissions_path}/PhotoLibrary"
  #   pod 'permission.LOCATION_WHEN_IN_USE', :path => "#{permissions_path}/LocationWhenInUse"
  

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    # HyperSDK configuration
    fuse_path = "./Pods/HyperSDK/Fuse.rb"
    clean_assets = false # Pass true to re-download all the assets
    if File.exist?(fuse_path)
      system("ruby", fuse_path.to_s, clean_assets.to_s)
    end
  end

end
