export const CREATE_ADDRESSES_REQUEST = "CREATE_ADDRESSES_REQUEST";
export const CREATE_ADDRESSES_SUCCESS = "CREATE_ADDRESSES_SUCCESS";
export const CREATE_ADDRESSES_FAILURE = "CREATE_ADDRESSES_FAILURE";

export const FETCH_ADDRESSES_REQUEST = "FETCH_ADDRESSES_REQUEST";
export const FETCH_ADDRESSES_SUCCESS = "FETCH_ADDRESSES_SUCCESS";
export const FETCH_ADDRESSES_FAILURE = "FETCH_ADDRESSES_FAILURE";
export const FETCH_ADDRESSES_DELETE = "FETCH_ADDRESSES_DELETE";

export const ADDRESS_DETAIL_REQUEST = "ADDRESS_DETAIL_REQUEST";
export const ADDRESS_DETAIL_SUCCESS = "ADDRESS_DETAIL_SUCCESS";
export const ADDRESS_DETAIL_FAIL = "ADDRESS_DETAIL_FAIL";

export const UPDATE_ADDRESS_REQUEST = "UPDATE_ADDRESS_REQUEST";
export const UPDATE_ADDRESS_SUCCESS = "UPDATE_ADDRESS_SUCCESS";
export const UPDATE_ADDRESS_FAIL = "UPDATE_ADDRESS_FAIL";

export const DELETE_ADDRESS_REQUEST = "DELETE_ADDRESS_REQUEST";
export const DELETE_ADDRESS_SUCCESS = "DELETE_ADDRESS_SUCCESS";
export const DELETE_ADDRESS_FAIL = "DELETE_ADDRESS_FAIL"; 