export const FETCH_BANNERS_REQUEST = "FETCH_BANNERS_REQUEST";
export const FETCH_BANNERS_SUCCESS = "FETCH_BANNERS_SUCCESS";
export const FETCH_BANNERS_FAILURE = "FETCH_BANNERS_FAILURE";

export const BANNER_DETAIL_REQUEST = "BANNER_DETAIL_REQUEST";
export const BANNER_DETAIL_SUCCESS = "BANNER_DETAIL_SUCCESS";
export const BANNER_DETAIL_FAIL = "BANNER_DETAIL_FAIL";

export const BANNER_PRODUCT_REQUEST = "BANNER_PRODUCT_REQUEST";
export const BANNER_PRODUCT_SUCCESS = "BANNER_PRODUCT_SUCCESS";
export const BANNER_PRODUCT_FAIL = "BANNER_PRODUCT_FAIL";

