export const FETCH_BRANDS_REQUEST = "FETCH_BRANDS_REQUEST";
export const FETCH_BRANDS_SUCCESS = "FETCH_BRANDS_SUCCESS";
export const FETCH_BRANDS_FAILURE = "FETCH_BRANDS_FAILURE";

export const FETCH_LIMITED_BRANDS_REQUEST = "FETCH_LIMITED_BRANDS_REQUEST";
export const FETCH_LIMITED_BRANDS_SUCCESS = "FETCH_LIMITED_BRANDS_SUCCESS";
export const FETCH_LIMITED_BRANDS_FAILURE = "FETCH_LIMITED_BRANDS_FAILURE";

export const BRAND_DETAIL_REQUEST = "BRAND_DETAIL_REQUEST";
export const BRAND_DETAIL_SUCCESS = "BRAND_DETAIL_SUCCESS";
export const BRAND_DETAIL_FAIL = "BRAND_DETAIL_FAIL";

export const BRAND_PRODUCT_REQUEST = "BRAND_PRODUCT_REQUEST";
export const BRAND_PRODUCT_SUCCESS = "BRAND_PRODUCT_SUCCESS";
export const BRAND_PRODUCT_FAIL = "BRAND_PRODUCT_FAIL";


