export const CREATE_CARTS_REQUEST = "CREATE_CARTS_REQUEST";
export const CREATE_CARTS_SUCCESS = "CREATE_CARTS_SUCCESS";
export const CREATE_CARTS_FAILURE = "CREATE_CARTS_FAILURE";

export const CREATE_REORDERED_CARTS_REQUEST = "CREATE_REORDERED_CARTS_REQUEST";
export const CREATE_REORDERED_CARTS_SUCCESS = "CREATE_REORDERED_CARTS_SUCCESS";
export const CREATE_REORDERED_CARTS_FAILURE = "CREATE_REORDERED_CARTS_FAILURE";

export const FETCH_CARTS_REQUEST = "FETCH_CARTS_REQUEST";
export const FETCH_CARTS_SUCCESS = "FETCH_CARTS_SUCCESS";
export const FETCH_CARTS_FAILURE = "FETCH_CARTS_FAILURE";

export const FETCH_CART_PRODUCTS_REQUEST = "FETCH_CART_PRODUCTS_REQUEST";
export const FETCH_CART_PRODUCTS_SUCCESS = "FETCH_CART_PRODUCTS_SUCCESS";
export const FETCH_CART_PRODUCTS_FAILURE = "FETCH_CART_PRODUCTS_FAILURE";

export const FETCH_CARTS_DELETE = "FETCH_CARTS_DELETE";

export const CART_DETAIL_REQUEST = "CART_DETAIL_REQUEST";
export const CART_DETAIL_SUCCESS = "CART_DETAIL_SUCCESS";
export const CART_DETAIL_FAIL = "CART_DETAIL_FAIL";

export const UPDATE_CART_REQUEST = "UPDATE_CART_REQUEST";
export const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS";
export const UPDATE_CART_FAIL = "UPDATE_CART_FAIL";

export const DELETE_CART_REQUEST = "DELETE_CART_REQUEST";
export const DELETE_CART_SUCCESS = "DELETE_CART_SUCCESS";
export const DELETE_CART_FAIL = "DELETE_CART_FAIL";

export const DELETE_CART_BY_VARIENT_REQUEST = "DELETE_CART_BY_VARIENT_REQUEST";
export const DELETE_CART_BY_VARIENT_SUCCESS = "DELETE_CART_BY_VARIENT_SUCCESS";
export const DELETE_CART_BY_VARIENT_FAIL = "DELETE_CART_BY_VARIENT_FAIL"; 