export const FETCH_COUPONS_REQUEST = "FETCH_COUPONS_REQUEST";
export const FETCH_COUPONS_SUCCESS = "FETCH_COUPONS_SUCCESS";
export const FETCH_COUPONS_FAILURE = "FETCH_COUPONS_FAILURE";

export const COUPON_DETAIL_REQUEST = "COUPON_DETAIL_REQUEST";
export const COUPON_DETAIL_SUCCESS = "COUPON_DETAIL_SUCCESS";
export const COUPON_DETAIL_FAIL = "COUPON_DETAIL_FAIL";

export const COUPON_PRODUCT_REQUEST = "COUPON_PRODUCT_REQUEST";
export const COUPON_PRODUCT_SUCCESS = "COUPON_PRODUCT_SUCCESS";
export const COUPON_PRODUCT_FAIL = "COUPON_PRODUCT_FAIL";

export const CREATE_COUPON_REQUEST = "CREATE_COUPON_REQUEST";
export const CREATE_COUPON_SUCCESS = "CREATE_COUPON_SUCCESS";
export const CREATE_COUPON_FAIL = "CREATE_COUPON_FAIL";

export const UPDATE_COUPON_REQUEST = "UPDATE_COUPON_REQUEST";
export const UPDATE_COUPON_SUCCESS = "UPDATE_COUPON_SUCCESS";
export const UPDATE_COUPON_FAIL = "UPDATE_COUPON_FAIL";

export const DELETE_COUPON_REQUEST = "DELETE_COUPON_REQUEST";
export const DELETE_COUPON_SUCCESS = "DELETE_COUPON_SUCCESS";
export const DELETE_COUPON_FAIL = "DELETE_COUPON_FAIL";