
export const GET_DELIVERYSTAFFS_REQUEST = "GET_DELIVERYSTAFFS_REQUEST";
export const GET_DELIVERYSTAFFS_SUCCESS = "GET_DELIVERYSTAFFS_SUCCESS";
export const GET_DELIVERYSTAFFS_FAILURE = "GET_DELIVERYSTAFFS_FAILURE";

export const DELIVERYSTAFF_DETAIL_REQUEST = "DELIVERYSTAFF_DETAIL_REQUEST";
export const DELIVERYSTAFF_DETAIL_SUCCESS = "DELIVERYSTAFF_DETAIL_SUCCESS";
export const DELIVERYSTAFF_DETAIL_FAIL = "DELIVERYSTAFF_DETAIL_FAIL";
export const DELIVERYSTAFF_DETAIL_DELETE = "DELIVERYSTAFF_DETAIL_DELETE";

export const CREATE_DELIVERYSTAFF_REQUEST = "CREATE_DELIVERYSTAFF_REQUEST";
export const CREATE_DELIVERYSTAFF_FAIL = "CREATE_DELIVERYSTAFF_FAIL";
export const CREATE_DELIVERYSTAFF_SUCCESS = "CREATE_DELIVERYSTAFF_SUCCESS";

export const UPDATE_DELIVERYSTAFF_REQUEST = "UPDATE_DELIVERYSTAFF_REQUEST";
export const UPDATE_DELIVERYSTAFF_FAIL = "UPDATE_DELIVERYSTAFF_FAIL";
export const UPDATE_DELIVERYSTAFF_SUCCESS = "UPDATE_DELIVERYSTAFF_SUCCESS";

export const UPDATE_DELIVERYSTAFFDP_REQUEST = "UPDATE_DELIVERYSTAFFDP_REQUEST";
export const UPDATE_DELIVERYSTAFFDP_FAIL = "UPDATE_DELIVERYSTAFFDP_FAIL";
export const UPDATE_DELIVERYSTAFFDP_SUCCESS = "UPDATE_DELIVERYSTAFFDP_SUCCESS";

export const DELETE_DELIVERYSTAFF_REQUEST = "DELETE_DELIVERYSTAFF_REQUEST";
export const DELETE_DELIVERYSTAFF_FAIL = "DELETE_DELIVERYSTAFF_FAIL";
export const DELETE_DELIVERYSTAFF_SUCCESS = "DELETE_DELIVERYSTAFF_SUCCESS";

export const DELETE_ALL_DELIVERYSTAFF_REQUEST = "DELETE_ALL_DELIVERYSTAFF_REQUEST";
export const DELETE_ALL_DELIVERYSTAFF_FAIL = "DELETE_ALL_DELIVERYSTAFF_FAIL";
export const DELETE_ALL_DELIVERYSTAFF_SUCCESS = "DELETE_ALL_DELIVERYSTAFF_SUCCESS";


