// constantUser.js
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const DELIVERYSTAFF_LOGIN_REQUEST = 'DELIVERYSTAFF_LOGIN_REQUEST';
export const DELIVERYSTAFF_LOGIN_SUCCESS = 'DELIVERYSTAFF_LOGIN_SUCCESS';
export const DELIVERYSTAFF_LOGIN_FAILURE = 'DELIVERYSTAFF_LOGIN_FAILURE';
