
export const GET_NOTIFICATIONS_REQUEST = "GET_NOTIFICATIONS_REQUEST";
export const GET_NOTIFICATIONS_SUCCESS = "GET_NOTIFICATIONS_SUCCESS";
export const GET_NOTIFICATIONS_FAIL = "GET_NOTIFICATIONS_FAIL";

export const GET_STAFF_NOTIFICATIONS_REQUEST = "GET_STAFF_NOTIFICATIONS_REQUEST";
export const GET_STAFF_NOTIFICATIONS_SUCCESS = "GET_STAFF_NOTIFICATIONS_SUCCESS";
export const GET_STAFF_NOTIFICATIONS_FAIL = "GET_STAFF_NOTIFICATIONS_FAIL";
export const GET_STAFF_NOTIFICATIONS_DELETE = "GET_STAFF_NOTIFICATIONS_DELETE";

export const UPDATE_NOTIFICATION_REQUEST = "UPDATE_NOTIFICATION_REQUEST";
export const UPDATE_NOTIFICATION_SUCCESS = "UPDATE_NOTIFICATION_SUCCESS";
export const UPDATE_NOTIFICATION_FAIL = "UPDATE_NOTIFICATION_FAIL";

export const DELETE_NOTIFICATION_REQUEST = "DELETE_NOTIFICATION_REQUEST";
export const DELETE_NOTIFICATION_SUCCESS = "DELETE_NOTIFICATION_SUCCESS";
export const DELETE_NOTIFICATION_FAIL = "DELETE_NOTIFICATION_FAIL";

export const NOTIFICATION_DETAIL_REQUEST = "NOTIFICATION_DETAIL_REQUEST";
export const NOTIFICATION_DETAIL_SUCCESS = "NOTIFICATION_DETAIL_SUCCESS";
export const NOTIFICATION_DETAIL_FAIL = "NOTIFICATION_DETAIL_FAIL";

