export const FETCH_PROMOS_REQUEST = "FETCH_PROMOS_REQUEST";
export const FETCH_PROMOS_SUCCESS = "FETCH_PROMOS_SUCCESS";
export const FETCH_PROMOS_FAILURE = "FETCH_PROMOS_FAILURE";

export const PROMO_DETAIL_REQUEST = "PROMO_DETAIL_REQUEST";
export const PROMO_DETAIL_SUCCESS = "PROMO_DETAIL_SUCCESS";
export const PROMO_DETAIL_FAIL = "PROMO_DETAIL_FAIL";
