export const FETCH_RECENT_ORDERS_REQUEST = "FETCH_RECENT_ORDERS_REQUEST";
export const FETCH_RECENT_ORDERS_SUCCESS = "FETCH_RECENT_ORDERS_SUCCESS";
export const FETCH_RECENT_ORDERS_FAILURE = "FETCH_RECENT_ORDERS_FAILURE";
export const FETCH_RECENT_ORDERS_DELETE = "FETCH_RECENT_ORDERS_DELETE";

export const RECENT_ORDER_DETAIL_REQUEST = "RECENT_ORDER_DETAIL_REQUEST";
export const RECENT_ORDER_DETAIL_SUCCESS = "RECENT_ORDER_DETAIL_SUCCESS";
export const RECENT_ORDER_DETAIL_FAIL = "RECENT_ORDER_DETAIL_FAIL";

export const CREATE_RECENT_ORDER_REQUEST = "CREATE_RECENT_ORDER_REQUEST";
export const CREATE_RECENT_ORDER_SUCCESS = "CREATE_RECENT_ORDER_SUCCESS";
export const CREATE_RECENT_ORDER_FAIL = "CREATE_RECENT_ORDER_FAIL";

export const UPDATE_RECENT_ORDER_REQUEST = "UPDATE_RECENT_ORDER_REQUEST";
export const UPDATE_RECENT_ORDER_SUCCESS = "UPDATE_RECENT_ORDER_SUCCESS";
export const UPDATE_RECENT_ORDER_FAIL = "UPDATE_RECENT_ORDER_FAIL";

export const DELETE_RECENT_ORDER_REQUEST = "DELETE_RECENT_ORDER_REQUEST";
export const DELETE_RECENT_ORDER_SUCCESS = "DELETE_RECENT_ORDER_SUCCESS";
export const DELETE_RECENT_ORDER_FAIL = "DELETE_RECENT_ORDER_FAIL";