export const FETCH_REQUESTS_REQUEST = "FETCH_REQUESTS_REQUEST";
export const FETCH_REQUESTS_SUCCESS = "FETCH_REQUESTS_SUCCESS";
export const FETCH_REQUESTS_FAILURE = "FETCH_REQUESTS_FAILURE";

export const FETCH_PENDING_REQUESTS_SUCCESS="FETCH_PENDING_REQUESTS_SUCCESS"
export const FETCH_PENDING_REQUESTS_REQUEST="FETCH_PENDING_REQUESTS_REQUEST"
export const FETCH_PENDING_REQUESTS_FAILURE="FETCH_PENDING_REQUESTS_FAILURE"
export const FETCH_PENDING_REQUESTS_DELETE ="FETCH_PENDING_REQUESTS_DELETE "

export const REQUEST_DETAIL_REQUEST = "REQUEST_DETAIL_REQUEST";
export const REQUEST_DETAIL_SUCCESS = "REQUEST_DETAIL_SUCCESS";
export const REQUEST_DETAIL_FAIL = "REQUEST_DETAIL_FAIL";

export const REQUEST_PRODUCT_REQUEST = "REQUEST_PRODUCT_REQUEST";
export const REQUEST_PRODUCT_SUCCESS = "REQUEST_PRODUCT_SUCCESS";
export const REQUEST_PRODUCT_FAIL = "REQUEST_PRODUCT_FAIL";

export const CREATE_REQUEST_REQUEST = "CREATE_REQUEST_REQUEST";
export const CREATE_REQUEST_SUCCESS = "CREATE_REQUEST_SUCCESS";
export const CREATE_REQUEST_FAIL = "CREATE_REQUEST_FAIL";

export const UPDATE_REQUEST_REQUEST = "UPDATE_REQUEST_REQUEST";
export const UPDATE_REQUEST_SUCCESS = "UPDATE_REQUEST_SUCCESS";
export const UPDATE_REQUEST_FAIL = "UPDATE_REQUEST_FAIL";

export const DELETE_REQUEST_REQUEST = "DELETE_REQUEST_REQUEST";
export const DELETE_REQUEST_SUCCESS = "DELETE_REQUEST_SUCCESS";
export const DELETE_REQUEST_FAIL = "DELETE_REQUEST_FAIL";