export const CREATE_RUNNING_ORDERS_REQUEST = "CREATE_RUNNING_ORDERS_REQUEST";
export const CREATE_RUNNING_ORDERS_SUCCESS = "CREATE_RUNNING_ORDERS_SUCCESS";
export const CREATE_RUNNING_ORDERS_FAILURE = "CREATE_RUNNING_ORDERS_FAILURE";
export const UPDATE_RUNNING_ORDER_REQUEST = "UPDATE_RUNNING_ORDER_REQUEST";
export const DELETE_RUNNING_ORDER_REQUEST = "DELETE_RUNNING_ORDER_REQUEST";