export const CREATE_WISHLISTS_REQUEST = "CREATE_WISHLISTS_REQUEST";
export const CREATE_WISHLISTS_SUCCESS = "CREATE_WISHLISTS_SUCCESS";
export const CREATE_WISHLISTS_FAILURE = "CREATE_WISHLISTS_FAILURE";

export const FETCH_WISHLISTS_REQUEST = "FETCH_WISHLISTS_REQUEST";
export const FETCH_WISHLISTS_SUCCESS = "FETCH_WISHLISTS_SUCCESS";
export const FETCH_WISHLISTS_FAILURE = "FETCH_WISHLISTS_FAILURE";
export const FETCH_WISHLISTS_DELETE = "FETCH_WISHLISTS_DELETE";

export const WISHLIST_DETAIL_REQUEST = "WISHLIST_DETAIL_REQUEST";
export const WISHLIST_DETAIL_SUCCESS = "WISHLIST_DETAIL_SUCCESS";
export const WISHLIST_DETAIL_FAIL = "WISHLIST_DETAIL_FAIL";

export const UPDATE_WISHLIST_REQUEST = "UPDATE_WISHLIST_REQUEST";
export const UPDATE_WISHLIST_SUCCESS = "UPDATE_WISHLIST_SUCCESS";
export const UPDATE_WISHLIST_FAIL = "UPDATE_WISHLIST_FAIL";

export const DELETE_WISHLIST_REQUEST = "DELETE_WISHLIST_REQUEST";
export const DELETE_WISHLIST_SUCCESS = "DELETE_WISHLIST_SUCCESS";
export const DELETE_WISHLIST_FAIL = "DELETE_WISHLIST_FAIL";